<?
$PERM["admin"]["2"]="R";
$PERM["admin"]["3"]="R";
$PERM["admin"]["4"]="R";
$PERM["admin"]["6"]="X";
$PERM["admin"]["5"]="R";
$PERM["admin"]["*"]="R";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>